# Generated by Django 6.0.3 on 2026-03-30 00:55

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('editora', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=100)),
                ('edicao', models.CharField(max_length=50)),
                ('sinopse', models.TextField()),
                ('capa', models.ImageField(upload_to='capas/')),
                ('quantidade', models.IntegerField()),
                ('endereco_prateleira', models.CharField(max_length=100)),
                ('observacoes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('aluno', 'Aluno'), ('funcionario', 'Funcionário'), ('exaluno', 'Ex-aluno')], max_length=20)),
                ('observacoes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField(default=datetime.datetime(2026, 4, 14, 0, 55, 0, 965059, tzinfo=datetime.timezone.utc))),
                ('data_notificacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('lembrete_enviado', models.BooleanField(default=False)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(default=django.utils.timezone.now)),
                ('data_devolucao_prevista', models.DateField(default=datetime.datetime(2026, 4, 14, 0, 55, 0, 964742, tzinfo=datetime.timezone.utc))),
                ('data_devolucao_real', models.DateField(blank=True, null=True)),
                ('renovacoes_concluidas', models.IntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuario')),
            ],
        ),
    ]
