# Generated by Django 6.0.3 on 2026-04-13 21:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao_prevista',
            field=models.DateField(default=datetime.datetime(2026, 4, 28, 21, 28, 54, 26920, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_expiracao',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 28, 21, 28, 54, 27264, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('exaluno', 'Ex-aluno')], max_length=20),
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuario')),
            ],
        ),
    ]
