# Generated by Django 6.0.4 on 2026-04-30 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_expiracao',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 15, 19, 59, 53, 869076, tzinfo=datetime.timezone.utc)),
        ),
    ]
