# Generated by Django 6.0.4 on 2026-05-01 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exemplar',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'managed': True},
        ),
    ]
