# Generated by Django 6.0.3 on 2026-04-13 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_emprestimo_data_devolucao_prevista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='codigo_catalografico',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='foi_renovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='nome_aluno',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='turma',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao_prevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_expiracao',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 28, 22, 28, 3, 631529, tzinfo=datetime.timezone.utc)),
        ),
    ]
