# Generated by Django 6.0.4 on 2026-05-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_add_descricao_livros_lista'),
        ('biblioteca', '0003_exemplar_livro_lista_descricao_lista_livros_and_more'),
    ]

    operations = [
    ]
