# Generated by Django 6.0.4 on 2026-04-18 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_emprestimo_codigo_catalografico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_expiracao',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 3, 17, 45, 38, 450534, tzinfo=datetime.timezone.utc)),
        ),
    ]
