# Generated by Django 6.0.4 on 2026-05-11 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_merge_20260508_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroLido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_marcado', models.DateField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitores', to='biblioteca.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_lidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livro Lido',
                'verbose_name_plural': 'Livros Lidos',
                'db_table': 'biblioteca_livrolido',
                'ordering': ['-data_marcado'],
                'unique_together': {('usuario', 'livro')},
            },
        ),
    ]
