# Generated by Django 6.0.4 on 2026-04-26 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_reserva_data_expiracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='capa',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='edicao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='endereco_prateleira',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='id',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='sinopse',
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='codigo_base',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='colecao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='id_livro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='livro',
            name='prateleira',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_expiracao',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 11, 23, 18, 43, 335455, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='livro',
            table='livro',
        ),
    ]
