# Generated by Django 6.0.4 on 2026-04-26 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_remove_livro_capa_remove_livro_edicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_expiracao',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 11, 23, 23, 58, 648617, tzinfo=datetime.timezone.utc)),
        ),
    ]
