# Generated by Django 6.0.4 on 2026-07-15 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_cargo_turma_usuario_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reserva_pendente', 'Reserva Pendente'), ('reserva_aceita', 'Reserva Aceita'), ('reserva_recusada', 'Reserva Recusada'), ('reserva_disponivel', 'Reserva Disponível'), ('reserva_expirada', 'Reserva Expirada'), ('fila_posicao', 'Posição na Fila'), ('devolucao_com_reserva', 'Devolução com Reserva'), ('prazo_2dias', 'Prazo em 2 dias'), ('prazo_amanha', 'Prazo Amanhã'), ('prazo_hoje', 'Prazo Hoje'), ('atraso', 'Atraso')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_email', models.BooleanField(default=False)),
                ('requer_acao', models.BooleanField(default=False)),
                ('acao_tomada', models.CharField(blank=True, choices=[('aceita', 'Aceita'), ('recusada', 'Recusada')], max_length=20, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
                ('emprestimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.emprestimo')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='biblioteca.reserva')),
            ],
            options={
                'db_table': 'biblioteca_notificacao',
                'ordering': ['-criada_em'],
            },
        ),
    ]
