# Generated by Django 6.0.4 on 2026-05-02 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_exemplar_options_alter_livro_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplar',
            name='livro',
            field=models.ForeignKey(db_column='id_livro', default=None, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lista',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lista',
            name='livros',
            field=models.ManyToManyField(blank=True, to='biblioteca.livro'),
        ),
        migrations.AddField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
