# Generated by Django 6.0.4 on 2026-05-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_exemplar_options_alter_livro_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lista',
            name='livros',
            field=models.ManyToManyField(blank=True, to='biblioteca.livro'),
        ),
    ]