# Generated by Django 6.0.4 on 2026-07-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_notificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['posicao_fila', 'data_reserva']},
        ),
        migrations.AddField(
            model_name='reserva',
            name='posicao_fila',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('aguardando_retirada', 'Aguardando Retirada'), ('concluida', 'Concluída'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada'), ('fila', 'Na Fila')], default='pendente', max_length=20),
        ),
    ]
