# Generated by Django 6.0.4 on 2026-07-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_alter_reserva_options_reserva_posicao_fila_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='categoria_grupo',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
