# Generated by Django 6.0.4 on 2026-07-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_livro_categoria_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, unique=True)),
                ('grupo', models.CharField(db_index=True, max_length=100)),
                ('criado_automaticamente', models.BooleanField(default=False)),
                ('revisado', models.BooleanField(default=False, help_text='Marque quando já tiver conferido se o grupo está correto.')),
            ],
            options={
                'verbose_name': 'Mapeamento de Categoria',
                'verbose_name_plural': 'Mapeamentos de Categoria',
                'db_table': 'biblioteca_categoria_grupo',
                'ordering': ['grupo', 'categoria'],
            },
        ),
    ]
